### ISSUE TITLE
Add ColorTranslator

### ISSUE THREAD

**Issue by VahidN** [CoreCompat/System.Drawing#1]
I'm using the netstandard1.3 version of this library and now it doesn't provide the `ColorTranslator` anymore.
```xml
<!-- These classes are not supported on netstandard -->
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemColors.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemPens.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\SystemBrushes.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\KnownColors.cs" />
<Compile Remove="$(SystemDrawingDir)System.Drawing\ColorTranslator.cs" />
```
Please add these classes, because old(?!) codes can't be compiled anymore.

**Comment by HarelM** [comment]
This is truly missing. I was using `FromHtml` method and I'm miss it. I can probably write it but I really don't want to since it belongs here...

**Comment by meysamSamanpour** [comment]
any news about this? if it is not possible to have the ForHtml methong is it possible to write a function to do that ? 
another question, please correct me if I did not get it correctly: adding support for System.drawing make your application not runnable at unix and it will bound to windows ?

**Comment by HarelM** [comment]
I didn't have time to wait for this.
Here's what I wrote (probably not perfect):
https://github.com/IsraelHikingMap/Site/blob/e4528002ff4346a7d7709f1cd408dca4b3157282/IsraelHiking.API/Services/ImageCreationService.cs#L401

**Comment by VahidN** [comment]
Start using the official https://www.nuget.org/packages/System.Drawing.Common/

**Comment by meysamSamanpour** [comment]
thanks that helped a lot
