### ISSUE TITLE
GDI+ status: NotImplemented

### ISSUE THREAD

**Issue by alexgoldstone** [CoreCompat/System.Drawing#12]
I am using:
```
runtime.osx.10.10-x64.CoreCompat.System.Drawing
```

I am using the following library:
```
https://github.com/yangzhongke/CaptchaGen.NetCore
```

I get the following error which seems to indicate that `System.Drawing.GDIPlus.CheckStatus` is used by the above library but is not implemented here. Are there any plans to add support for this?

```
'System.NotImplementedException: The requested feature is not implemented [GDI+ status: NotImplemented]
   at System.Drawing.GDIPlus.CheckStatus(Status status)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at CaptchaGen.NetCore.ImageFactory.BuildImage(String captchaCode, Int32 imageHeight, Int32 imageWidth, Int32 fontSize, Int32 distortion, ImageFormatType imgType)
   at api.Controllers.CaptchaController.Create() in /api/Controllers/CaptchaController.cs:line 55'
```

**Comment by VahidN** [comment]
The official https://www.nuget.org/packages/System.Drawing.Common/ is out. give it a try.

**Comment by qmfrederik** [comment]
You (or CaptchaGen) trying to create an image in a format which is not supported by (your copy of) libgdiplus, the native library backing System.Drawing.Common and CoreCompat.System.Drawing.

You'll get the same error with both libraries.

**Comment by alexgoldstone** [comment]
For anyone searching for answers to the same issue...

I changed to use `System.Drawing.Common` per the suggestion from @VahidN 

This required me to also install `mono-libgdiplus` using:
```
brew install mono-libgdiplus
```

However the actual issue was inline with the comment from @qmfrederik as the library was specifying `Format64bppArgb`. I changed to `Format32bppArgb` and this worked.
