### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by Gillardo** [CoreCompat/System.Drawing#2]
Where is the core 2.0 version on nuget?  Cant seem to find it.

Using this package, does it mean that all references to System.Drawing will now work, even if i have thrird party code that references system.Drawing? As at the moment i have errors like so

![image](https://user-images.githubusercontent.com/7406381/26920982-8d8f3ee2-4c32-11e7-8e76-97df719831d7.png)

**Comment by qmfrederik** [comment]
@Gillardo Try https://www.nuget.org/packages/CoreCompat.System.Drawing.v2 (notice the .v2 suffix)

**Comment by Gillardo** [comment]
Sorry, my mistake 👍 

Tried that and although works on my code, the library i am using is referencing System.Drawing (Font class) and it errors on that line... gutted
