### ISSUE TITLE
The assembly does not have a strong name.

### ISSUE THREAD

**Issue by brunin2509** [CoreCompat/System.Drawing#3]
Hello, guys! 

I am trying to use CoreCompat.System.Drawing.v2, but I am receiving the following error:

> Referenced assembly 'CoreCompat.System.Drawing, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

Therefore, I wondered whether your assembly is actually strong named, and, if it's not, whether it is in your plans to make it strong named.

Thank you!

**Comment by qmfrederik** [comment]
You're correct, the package is not strongly named. Can you check [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25718-03)?

**Comment by qmfrederik** [comment]
I'm going to close this issue as this package has been superseded by System.Drawing.Common. Please file issues over at dotnet/corefx and mention me if you have issues with System.Drawing.Common.
