### ISSUE TITLE
Color type is defined in two different assemblies

### ISSUE THREAD

**Issue by Jose-CF** [CoreCompat/System.Drawing#4]
error CS0433: The type 'Color' exists in both 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by paladin2005** [comment]
How do you solved this?

**Comment by mrgleba** [comment]
Package CoreCompat.System.Drawing.v2 doesn't contain the Color type.
Either you're referencing CoreCompat.System.Drawing or a library that you are using references CoreCompat.System.Drawing rather than CoreCompat.System.Drawing.v2.

**Comment by paladin2005** [comment]
I just update epplus.core and solved this issue.

**Comment by Jose-CF** [comment]
@mrgleba mmm do not remember which version of CoreCompat was used.
Thank you @paladin2005

**Comment by DoctorChip** [comment]
Similarly, as of today, version 1.0.0beta006 of CoreCompat.System.Drawing.

The type 'Color' exists in both 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592' and 'System.Drawing.Primitives, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by qmfrederik** [comment]
For those on .NET Standard/Core 2.0, can you try to use the [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25718-03) package instead?

**Comment by DoctorChip** [comment]
@qmfrederik Works great, thanks for your help.

**Comment by Jose-CF** [comment]
@qmfrederik thank you for the update!
Do you know by a chance, is that package behaving well in Linux ?! Or does it misses some native libraries...?

**Comment by qmfrederik** [comment]
@Jose-CF It works well on Linux, but it will require you to install `libgdiplus` via your Linux package manager.

Some Linux distributions (RedHat,...) include very old versions of libgdiplus. In that case, it may be best to install an up-to-date version of libgdiplus based on Mono's package feed. You can find information on how to enable that here: http://www.mono-project.com/download/#download-lin

You _do not need to install Mono_, just libgdiplus from Mono's package repository.

**Comment by Jose-CF** [comment]
Great, thank you so much for the tip

**Comment by ruchit07** [comment]
Remove package CoreCompat.System.Drawing and install [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25718-03)

And give reference of System.Drawing.Common

**Comment by qmfrederik** [comment]
I'm going to close this issue as this package has been superseded by System.Drawing.Common. Please file issues over at dotnet/corefx and mention me if you have issues with System.Drawing.Common.
