### ISSUE TITLE
Reduce visibility of Consts class

### ISSUE THREAD

**Issue by lechu445** [CoreCompat/System.Drawing#6]
Problem:
Class Consts is visible everywhere in projects using CoreCompat/System.Drawing. These projects could have defined their own Consts class, so the Consts class and Consts class from CoreCompat/System.Drawing confilct each other.

Suggestion of solution:
Add namespace to Consts class or change visibilty from public to internal.

**Comment by qmfrederik** [comment]
Thanks, this should be fixed in [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25718-03)

**Comment by qmfrederik** [comment]
I'm going to close this issue as this package has been superseded by System.Drawing.Common. Please file issues over at dotnet/corefx and mention me if you have issues with System.Drawing.Common.
