### ISSUE TITLE
centos 7.2 error

### ISSUE THREAD

**Issue by simpleway2016** [CoreCompat/System.Drawing#8]
It works in windows 10. 
I included runtime.linux-x64.CoreCompat.System.Drawing.
But also throw exception in centos 7.

error message:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL78BBCTMK3S", Request id "0HL78BBCTMK3S:00000001": An unhandled exception was thrown by the application.
System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdiplus': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Drawing.GDIPlus.GdiplusStartup(UInt64& token, GdiplusStartupInput& input, GdiplusStartupOutput& output)
   at System.Drawing.GDIPlus..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.GDIPlus.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, PixelFormat format, IntPtr scan0, IntPtr& bmp)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)

**Comment by mrgleba** [comment]
Probably a missing dependency for libgdipus.
Try runing "ldd libgdiplus.so" and look for what's missing.
It was libpcre in my case on Fedora.

Anyhow it's safer to install libgdiplus from system repo rather than using
"runtime.linux-x64.CoreCompat.System.Drawing".

**Comment by qmfrederik** [comment]
If I recall correctly, the `.so` file for `libgdiplus` is named `libgdiplus.so.0` on CentOS (see https://centos.pkgs.org/7/epel-x86_64/libgdiplus-2.10-9.el7.x86_64.rpm.html). CoreCompat.System.Drawing is looking for `libgdiplus.so` so that doesn't work.

On CentOS, you need to install the [`libgdiplus-devel`](https://centos.pkgs.org/7/epel-x86_64/libgdiplus-devel-2.10-9.el7.x86_64.rpm.html) package.

Can you try with libgdiplus-devel and see if it works?

**Comment by simpleway2016** [comment]
I use "ldd libgdiplus.so"，and then found centos miss file "	libpcre.so.3 "，so i copy this file from ubuntu，and put it in /lib64. Finally my program works.

**Comment by mrgleba** [comment]
Actoually you don't have to install files from ubuntu.
It's enough to create a symbolic link libpcre.so.3 in the lib dir to the proper libpcre.so library and it'll work.

**Comment by mrgleba** [comment]
@qmfrederik simply creating a link libgdiplus.so also works in this case. There is no need for devel rpm.

**Comment by qmfrederik** [comment]
@mrgleba Yep, that works as well and may even be more elegant. Thanks for the info!

**Comment by qmfrederik** [comment]
The symlink/devel package workaround should work for thos on .NET Standard/Core 1.0.

For those on .NET Standard/Core 2.0, the [System.Drawing.Common](https://www.nuget.org/packages/System.Drawing.Common/4.5.0-preview1-25718-03) package will fix this permanently.

**Comment by qmfrederik** [comment]
Hi everyone on this thread,

The long-term solution for this was dotnet/corefx#17135, but I learned today that this won't make it for .NET Core 2.1.

If you're using .NET Core and System.Drawing, would you mind voting for that issue (clicking the 'thumbs up' emoji at the issue description would o it)?

Thanks!
